import type { Metadata } from "next";
import { Inria_Serif, Inter } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import { PageTransition } from "@/components/page-transition";
import "./globals.css";

const inriaSerif = Inria_Serif({
  variable: "--font-inria-serif",
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${inriaSerif.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col relative bg-background">
        {/* Global Background Image / Blur */}
        <div 
          className="absolute top-0 left-0 w-full h-[600px] z-[-1] bg-cover bg-center bg-no-repeat pointer-events-none"
          style={{ backgroundImage: "url('/review-page-image.svg')" }}
        >
          <div className="absolute inset-0 bg-gradient-to-b from-transparent via-background/40 to-background" />
        </div>
        <PageTransition>
          {children}
        </PageTransition>
        <Toaster />
      </body>
    </html>
  );
}
